# Generated by Django 5.0.4 on 2024-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dajngo_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_user', models.CharField(max_length=500)),
                ('email_for_user', models.CharField(max_length=500)),
                ('password_for_user', models.CharField(max_length=500)),
            ],
        ),
    ]
